# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-24 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='travel_date_from',
            field=models.DateTimeField(default='1997-08-01'),
        ),
        migrations.AddField(
            model_name='trip',
            name='travel_date_to',
            field=models.DateTimeField(default='1997-08-31'),
        ),
    ]
